name: iridium_reader_widget
description: Plug and play ebook reader widget
version: 0.0.1
publish_to: none
homepage: https://iridium.rocks

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  mno_commons:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/commons
  mno_navigator:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/navigator
  mno_opds:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/opds
  mno_server:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/server
  mno_shared:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/shared
  mno_streamer:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/streamer
  mno_webview:
    git:
      url: https://github.com/bankuoniichan/FlutterEbookApp.git
      ref: "pub-0.0.6"
      path: packages/iridium/components/webview
  #  cupertino_icons: ^1.0.5
  dartx: ^1.1.0
  dfunc: ^0.9.0
  fimber: ^0.6.6
  flutter_bloc: ^8.1.3
  flutter_fimber: ^0.6.5
  flutter_inappwebview: ^5.7.2+3
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.1
  path_provider: ^2.0.15
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider.git
      ref: master # branch name

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
